// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_PUBLIC_OMNICART_BACKEND_URL: string;
	NEXT_PUBLIC_OMNICART_PUBLISHABLE_KEY: string;
}
